# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiServerNode
  labels:
    app: apiServerNode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiServerNode
  template:
    metadata:
      labels:
        app: apiServerNode
    spec:
      containers:
      - name: apiServerNode
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true

